### ISSUE TITLE
seven daily hobbit meals

### ISSUE THREAD

**Issue by ungoldman** [movieclub/Day-of-the-Hobbits#1]
@mbcharbonneau may I suggest adjusting your schedule to accommodate the [Seven Daily Hobbit Meals](http://askmiddlearth.tumblr.com/post/41765286488/the-seven-daily-hobbit-meals).
- 7:00am – Breakfast
- 9:00am – Second Breakfast
- 11:00am – Elevenses
- 1:00pm – Luncheon
- 4:00pm – Afternoon Tea
- 6:00pm – Dinner
- 8:00pm – Supper

**Comment by aranasaurus** [comment]
:+1:

**Comment by ungoldman** [comment]
(six, if you're following the rules from the books)

**Comment by bcomnes** [comment]
Can I come!?

**Comment by jyaganeh** [comment]
![](http://professionalfangirls.com/wp-content/uploads/2014/10/TheHobbit_WorldPremiere_ThumbsUp.jpg)

**Comment by mbcharbonneau** [comment]
Oh wow how could I forget about the seven daily hobbit meals?! Updated the readme accordingly.

@bcomnes yes it would be awesome if you came! DM or email me if you need my address.

**Comment by ungoldman** [comment]
Here are some recipes that may be relevant.

http://lotrscrapbook.bookloaf.net/other/recipes.html
