### ISSUE TITLE
The Hobbit: The Tolkien Edit

### ISSUE THREAD

**Issue by ungoldman** [movieclub/Day-of-the-Hobbits#2]
I have in my possession a 4 hour edition of the Hobbit movies (the "good parts" version) if you are interested. Here is its description and justification: https://tolkieneditor.wordpress.com/. It's not, strictly speaking, a purist approach, but may make the first half of your marathon a bit easier.

**Comment by bcomnes** [comment]
![](http://img.pandawhale.com/post-22829-Evangeline-Lilly-Orlando-Bloom-1yjn.gif)
